# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-07 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190207_1335'),
        ('rango', '0009_auto_20190207_1319'),
    ]

    operations = [
    ]
